// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { MedicalProtectionCalculator } from './MedicalProtectionCalculator'
beforeEach(() => sessionStorage.clear())
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.useRealTimers() })
it('keeps cards independent, validates the whole combination and collapses detail', () => {
  render(<MedicalProtectionCalculator advisor="test" />)
  fireEvent.change(screen.getByLabelText('投保翌年岁（ANB）'), { target: { value: '41' } })
  fireEvent.change(screen.getByLabelText('投保额（USD）'), { target: { value: '100000' } })
  expect(document.querySelector('details')?.open).toBe(false)
  fireEvent.click(screen.getByRole('button', { name: '新增保险' }))
  expect(screen.getByText('完善全部保险信息后显示合计，不计入不完整测算。')).toBeTruthy()
  const second = within(screen.getByLabelText('保险 2'))
  fireEvent.change(second.getByLabelText('保险产品'), { target: { value: 'CIE3' } })
  expect((second.getByLabelText('供款期') as HTMLSelectElement).value).toBe('10')
  expect((within(screen.getByLabelText('保险 1')).getByLabelText('供款期') as HTMLSelectElement).value).toBe('5')
  fireEvent.change(second.getByLabelText('投保额（USD）'), { target: { value: '200000' } })
  expect(screen.getByText('首年保费合计')).toBeTruthy()
  const confirm = vi.spyOn(window, 'confirm').mockReturnValue(false)
  fireEvent.click(second.getByRole('button', { name: '移除保险 2' }))
  expect(screen.getByLabelText('保险 2')).toBeTruthy()
  confirm.mockReturnValue(true)
  fireEvent.click(second.getByRole('button', { name: '移除保险 2' }))
  expect(screen.queryByLabelText('保险 2')).toBeNull()
})
it('preserves unreadable draft and isolates advisors', () => {
  sessionStorage.setItem('jojo-medical-v1:broken', 'invalid')
  render(<MedicalProtectionCalculator advisor="broken" />)
  fireEvent.change(screen.getByLabelText('投保翌年岁（ANB）'), { target: { value: '41' } })
  expect(sessionStorage.getItem('jojo-medical-v1:broken')).toBe('invalid')
  expect(screen.getByRole('alert').textContent).toContain('原记录未被覆盖')
  cleanup()
  render(<MedicalProtectionCalculator advisor="other" />)
  expect((screen.getByLabelText('投保翌年岁（ANB）') as HTMLInputElement).value).toBe('')
})
it('uses birthday age for premiums and restores the manual age when cleared', () => {
  vi.useFakeTimers(); vi.setSystemTime(new Date('2026-09-08T04:00:00Z'))
  render(<MedicalProtectionCalculator advisor="birthday" />)
  const age = screen.getByLabelText('投保翌年岁（ANB）') as HTMLInputElement
  fireEvent.change(age, { target: { value: '41' } })
  fireEvent.change(screen.getByLabelText('投保额（USD）'), { target: { value: '100000' } })
  const oldPremium = within(screen.getByLabelText('保险 1')).getByText('14,585.00')
  expect(oldPremium).toBeTruthy()
  fireEvent.change(screen.getByLabelText('出生日期'), { target: { value: '1990-09-08' } })
  expect(age.value).toBe('37'); expect(age.readOnly).toBe(true)
  expect(within(screen.getByLabelText('保险 1')).queryByText('14,585.00')).toBeNull()
  fireEvent.change(screen.getByLabelText('出生日期'), { target: { value: '2027-01-01' } })
  expect(screen.getByRole('alert').textContent).toBe('出生日期不能晚于今天')
  expect(screen.queryByText('首年保费合计')).toBeNull()
  fireEvent.change(screen.getByLabelText('出生日期'), { target: { value: '' } })
  expect(age.value).toBe('41'); expect(age.readOnly).toBe(false)
})
it('refreshes the auto age at Hong Kong midnight and on returning to the page', () => {
  vi.useFakeTimers(); vi.setSystemTime(new Date('2026-09-07T15:59:59Z'))
  render(<MedicalProtectionCalculator advisor="midnight" />)
  fireEvent.change(screen.getByLabelText('出生日期'), { target: { value: '1990-09-08' } })
  expect((screen.getByLabelText('投保翌年岁（ANB）') as HTMLInputElement).value).toBe('36')
  vi.setSystemTime(new Date('2026-09-07T16:00:00Z'))
  fireEvent.focus(window)
  expect((screen.getByLabelText('投保翌年岁（ANB）') as HTMLInputElement).value).toBe('37')
})
it('accepts legacy drafts without birthday and preserves manual input', () => {
  render(<MedicalProtectionCalculator advisor="legacy" />)
  fireEvent.change(screen.getByLabelText('投保翌年岁（ANB）'), { target: { value: '41' } })
  cleanup()
  const draft = JSON.parse(sessionStorage.getItem('jojo-medical-v1:legacy')!)
  delete draft.birthday
  sessionStorage.setItem('jojo-medical-v1:legacy', JSON.stringify(draft))
  render(<MedicalProtectionCalculator advisor="legacy" />)
  expect(screen.queryByRole('alert')).toBeNull()
  expect((screen.getByLabelText('投保翌年岁（ANB）') as HTMLInputElement).value).toBe('41')
})
it('switches to hospital-specific inputs, restricts invalid combinations and restores drafts', () => {
  render(<MedicalProtectionCalculator advisor="hospital" />)
  fireEvent.change(screen.getByLabelText('投保翌年岁（ANB）'), { target: { value: '41' } })
  fireEvent.change(screen.getByLabelText('保险产品'), { target: { value: 'MCVIP' } })
  expect(screen.queryByLabelText('投保额（USD）')).toBeNull()
  expect(screen.queryByLabelText('供款期')).toBeNull()
  expect(screen.getByText('2,789.80', { selector: 'strong' })).toBeTruthy()
  fireEvent.change(screen.getByLabelText('保障计划'), { target: { value: '1' } })
  const excess = screen.getByLabelText('年度自付额（USD）') as HTMLSelectElement
  expect(excess.value).toBe('1'); expect(excess.options[0].disabled).toBe(true)
  fireEvent.change(screen.getByLabelText('门诊宝'), { target: { value: 'true' } })
  expect(document.querySelector('details')?.open).toBe(false)
  cleanup(); render(<MedicalProtectionCalculator advisor="hospital" />)
  expect((screen.getByLabelText('门诊宝') as HTMLSelectElement).value).toBe('true')
  fireEvent.change(screen.getByLabelText('保险产品'), { target: { value: 'VIP' } })
  expect(screen.queryByLabelText('门诊宝')).toBeNull()
  expect(screen.getByText('12,000.00')).toBeTruthy()
  fireEvent.change(screen.getByLabelText('测算年数'), { target: { value: '' } })
  expect(screen.queryByText('首年保费合计')).toBeNull()
})
